// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybifjdlelpvgzmzvgwls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InliaWZqZGxlbHB2Z3ptenZnd2xzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU0Mjg2NTUsImV4cCI6MjA4MTAwNDY1NX0.uriVOIaURJbw8z3JJ0GIlrdPo96XfyZlUsOudd7-Qjg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});